server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mariadb2?serverTimezone=UTC&useSSL=false
    username: stest
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver